from django.urls import path
from . import views
urlpatterns = [
    path('get_members_mssql',views.GetMemberInfo.as_view()),
    path('get_count',views.Get_Count.as_view()),
    path('search_member_mssql',views.search_members),
    # path('add_member_mssql',views.add_member),
    # path('add_member',views.add_member_db2),
    # path('update_member_mssql',views.UpdateMemberInfo.as_view()),
    # path('update_member',views.UpdateMemberInfoDB2.as_view()),
    path('get_recent_data',views.MostRecentDataView.as_view()),
    path('get_dependent_data_mssql',views.GetMemberAndDependentsView.as_view()),
    path('get_daily_count',views.GetMemberCountView.as_view()),
    path('get_claims',views.GetTotalClaimsDataView.as_view()),
    path('get_claim_no_data',views.GetClaimsDataUsingClaimNoView.as_view()),
    path('get_claims_using_ssn',views.GetClaimsDataView.as_view()),
    path('get_claim_count',views.GET_CLAIMS_COUNT.as_view()),
    path('download_claims_report',views.DownloadClaimsReport.as_view()),
    # path('add_dependent_mssql',views.add_dependents),
    # path('add_dependent',views.add_dependents_db2),
    # path('add_alternate',views.AlternativeAddressTableCreate.as_view()),
    # path('add_notes',views.NotesEntryCreateView.as_view()),
    path('get_notes',views.NotesEntryListView.as_view()),
    path('login',views.LoginAPIView.as_view()),
    path('register',views.RegisterAPIView.as_view()),
    path('get_alternate',views.Get_AlternateAddressData.as_view()),
    # path('update_alternate',views.AlternativeAddressTableUpdate.as_view()),
    path('search_member',views.serach_members_db2),
    path('get_dependent_data',views.GetMemberAndDependentsViewDB2.as_view()),
    path('get_members',views.GetMemberInfoDB2.as_view()),
    path('get_eligibility',views.GetEligibilityDataDB2.as_view()),
    # path('update_eligibility',views.UpdateEligibilityDataDB2.as_view()),
    path('search_eligibility',views.serach_for_eligibility),
    path('get_eob',views.generate_pdf),
    path('get_termed_data',views.TermedMembersView.as_view()),
    path('term_by_date',views.GetDataByTermDate.as_view())
]